# Generated by Django 4.2.2 on 2023-06-13 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=5)),
                ('numero', models.IntegerField()),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanica.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idFoto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idPregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rut', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=15)),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_usuario_set', to='botanica.pregunta')),
                ('idRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_usuario_set', to='botanica.pregunta')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanica.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fVenta', models.ImageField(upload_to='mascota')),
                ('total', models.IntegerField()),
                ('fDespacho', models.ImageField(upload_to='mascota')),
                ('estatus', models.TextField(max_length=200)),
                ('carrito', models.TextField(max_length=200)),
                ('idDireccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanica.direccion')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanica.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanica.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanica.usuario'),
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('idDetalle', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subTotal', models.IntegerField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanica.producto')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanica.venta')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='idRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanica.region'),
        ),
    ]
